name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag pattern be like: 'v1.2.1'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.2.3"
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get

      - uses: dart-lang/setup-dart@v1
      - name: Install dart dependencies
        run: dart pub get
      - name: Publish
        run: dart pub publish --force
